In [2]:
import pandas as pd 

df = pd.read_csv("data/test_zeroshot.csv")

df.head()

                                                text  label
0  The patient is 40 years old. She had 7 pregnan...      0
1  The patient is 47 years old. She had 10 pregna...      0
2  The patient is 26 years old. She had 2 pregnan...      0
3  The patient is 34 years old. She had 7 pregnan...      1
4  The patient is 22 years old. She had 2 pregnan...      0

In [4]:
df = pd.read_csv("data/train_finetune.csv")

df.head()

                                                text  label
0  The patient is 24 years old. She had 1 pregnan...      0
1  The patient is 40 years old. She had 5 pregnan...      0
2  The patient is 25 years old. She had 2 pregnan...      0
3  The patient is 29 years old. She had 1 pregnan...      0
4  The patient is 22 years old. She had 0 pregnan...      0

In [6]:
df["text"][0]

'The patient is 24 years old. She had 1 pregnancy. Her glucose level is 90.0. Her blood pressure is 62.0. Her skin thickness is 12.0. Her insulin level is 43.0. Her BMI is 27.2. Her diabetes pedigree function is 0.58. Based on these values, the patient is not diabetic.'

In [7]:
df = pd.read_csv("data/test_finetune.csv")

df.head()

                                                text  label
0  The patient is 40 years old. She had 7 pregnan...      0
1  The patient is 47 years old. She had 10 pregna...      0
2  The patient is 26 years old. She had 2 pregnan...      0
3  The patient is 34 years old. She had 7 pregnan...      1
4  The patient is 22 years old. She had 2 pregnan...      0

In [8]:
df["text"][0]

'The patient is 40 years old. She had 7 pregnancies. Her glucose level is 159.0. Her blood pressure is 64.0. Her skin thickness is 0.0. Her insulin level is 0.0. Her BMI is 27.4. Her diabetes pedigree function is 0.294. Is this patient diabetic or not diabetic?'